In [1]:
# This reads in the raw literature abundances and calculates a final
# value, to test the functionality of our pipeline

# Created 2019 June 16 by E.S.

In [2]:
import pandas as pd
import numpy as np

In [3]:
stem = ("../rrlyrae_metallicity/src/high_res_feh/")

### Clementini+ 1995 high-res [Fe/H] values

### (see Table 12 in Clementini, G., Carretta, E., Gratton, R., et al. 1995, AJ, 657 110, 2319)

In [3]:
data_C15 = pd.read_csv(stem + "clementini_1995_abundances.dat")

In [7]:
# Clementini+ 1995 net Fe/H values are the average Fe/H values for FeI and FeII as calculated via log(eps) + const., 
# where the const. is the solar value for either the FeI or FeII lines, as indicated in their Table 12. But they
# don't calculate an error, which we calculate by adding the errors of log(eps) in quadrature. This may be an 
# underestimate, however, since we are treating the error in the solar log(eps) values to be zero

# (They do mention in last paragraph of Sec. 4.1.2. that they consider effects of solar reference variations in Table 11
# but it's not clear if these are included in Table 12.)

In [23]:
data_C15["err_log_eps"] = np.sqrt(np.power(0.5*data_C15["err_log_eps_feI"],2) + 
                              np.power(0.5*data_C15["err_log_eps_feII"],2))
# note the 0.5* is due to the fact that the net Fe/H value is an average of two numbers

data_C15["err_feh"] = data_C15["err_log_eps"]

In [24]:
# print all the data

data_C15

,name,feh,log_eps_feI,err_log_eps_feI,log_eps_feII,err_log_eps_feII,err_feh,err_log_eps
0,X Ari,-2.50,5.04,0.13,5.02,0.13,0.091924,0.091924
1,RR Cet,-1.38,6.18,0.16,6.13,0.06,0.085440,0.085440
2,VX Her,-1.58,5.82,0.12,6.08,0.14,0.092195,0.092195
3,RR Lyr,-1.39,6.14,0.13,6.14,0.13,0.091924,0.091924
4,V445 Oph,0.17,7.74,0.16,7.66,0.17,0.116726,0.116726

In [ ]:
# Generally, to get Fe/H from log(eps), use Anstee+ 1997 solar value of log(N_FeI/N_H) + 12 = (7.51+-0.01) like this:
# [Fe/H] = log(eps) - (7.51+-0.01)

### Lambert et al. (1996)

### (see Table 3 in Lambert, D., Heath, J., Lemke, M., & Drake, J. 1996, ApJSS, 103, 183)

In [25]:
data_L96 = pd.read_csv(stem + "lambert_1996_abundances.dat")

In [26]:
data_L96

,name,log_eps_fe_spec,log_eps_feI_phot,err_log_eps_feI_phot,log_eps_feII_phot,err_log_eps_feII_phot
0,SW And,7.18,7.10,0.10,7.27,0.12
1,X Ari,5.03,4.76,0.08,4.97,0.09
2,RS Boo,6.89,6.96,0.11,7.12,0.08
3,XZ Cyg,6.00,5.75,0.13,6.06,0.13
4,DX Del,7.00,7.05,0.09,7.16,0.08
5,SU Dra,5.76,5.55,0.09,5.71,0.09
6,XZ Dra,6.70,6.57,0.10,6.75,0.11
7,SV Eri,5.40,5.27,0.08,5.59,0.06
8,RR Leo,6.11,5.97,0.11,6.34,0.10
9,TT Lyn,5.96,5.88,0.08,6.18,0.06
10,AV Peg,7.29,7.16,0.09,7.47,0.06
11,DH Peg,6.19,6.13,0.09,6.29,0.06
12,AR Per,7.27,7.10,0.08,7.28,0.07
13,VY Ser,5.58,5.42,0.08,5.75,0.06
14,T Sex,5.95,5.76,0.12,6.01,0.09
15,TU UMa,5.95,5.87,0.08,6.06,0.08
16,UU Vir,6.81,6.66,0.12,6.72,0.07

In [29]:
# We want the log_eps_fe_spec (see research journal, 2019 June 18). Assign errors to them by applying
# the largest photometric error uniformly. In the final Fe/H error, we need to add the error in log(eps)
# in quadrature with 0.01 (the error in Anstee+ 1997 for the solar value of log(eps))

data_L96["err_log_eps_fe_spec"] = np.max([data_L96["err_log_eps_feI_phot"],data_L96["err_log_eps_feI_phot"]])

data_L96["err_feh"] = np.sqrt(np.power(data_L96["err_log_eps_fe_spec"],2) + 
                              np.power(0.01,2))

# convert log(eps) to Fe/H
data_L96["feh"] = np.subtract(data_L96["log_eps_fe_spec"], 7.51)

In [31]:
data_L96

,name,log_eps_fe_spec,log_eps_feI_phot,err_log_eps_feI_phot,log_eps_feII_phot,err_log_eps_feII_phot,err_log_eps_fe_spec,err_feh,feh
0,SW And,7.18,7.10,0.10,7.27,0.12,0.13,0.130384,-0.33
1,X Ari,5.03,4.76,0.08,4.97,0.09,0.13,0.130384,-2.48
2,RS Boo,6.89,6.96,0.11,7.12,0.08,0.13,0.130384,-0.62
3,XZ Cyg,6.00,5.75,0.13,6.06,0.13,0.13,0.130384,-1.51
4,DX Del,7.00,7.05,0.09,7.16,0.08,0.13,0.130384,-0.51
5,SU Dra,5.76,5.55,0.09,5.71,0.09,0.13,0.130384,-1.75
6,XZ Dra,6.70,6.57,0.10,6.75,0.11,0.13,0.130384,-0.81
7,SV Eri,5.40,5.27,0.08,5.59,0.06,0.13,0.130384,-2.11
8,RR Leo,6.11,5.97,0.11,6.34,0.10,0.13,0.130384,-1.40
9,TT Lyn,5.96,5.88,0.08,6.18,0.06,0.13,0.130384,-1.55
10,AV Peg,7.29,7.16,0.09,7.47,0.06,0.13,0.130384,-0.22
11,DH Peg,6.19,6.13,0.09,6.29,0.06,0.13,0.130384,-1.32
12,AR Per,7.27,7.10,0.08,7.28,0.07,0.13,0.130384,-0.24
13,VY Ser,5.58,5.42,0.08,5.75,0.06,0.13,0.130384,-1.93
14,T Sex,5.95,5.76,0.12,6.01,0.09,0.13,0.130384,-1.56
15,TU UMa,5.95,5.87,0.08,6.06,0.08,0.13,0.130384,-1.56
16,UU Vir,6.81,6.66,0.12,6.72,0.07,0.13,0.130384,-0.70

### Fernley & Barnes (1997)

### (see data on CDS, as well as Sec. 4.1 in Fernley, J., & Barnes, T. 1997, A&ASS, 125, 313)

In [13]:
data_F97 = pd.read_csv("fernley_1997_abundances.dat")

In [14]:
data_F97

        name   feh  err_feh
0     SW And -0.24     0.13
1     AT And -1.32     0.13
2     CI And -0.55     0.13
3     BR Aqr -0.72     0.13
4     BH Aur  0.14     0.13
5     RS Boo -0.33     0.13
6     AE Boo -1.34     0.13
7     UY Cam -1.51     0.13
8      Z CVn -1.66     0.13
9     SS CVn -1.07     0.13
10    UZ CVn -1.44     0.13
11    AA CMi -0.14     0.13
12  V363 Cas -0.38     0.13
13    EZ Cep -0.01     0.13
14    RR Cet -1.49     0.13
15    RZ Cet -1.13     0.13
16     U Com -1.19     0.13
17    DM Cyg -0.06     0.13
18    SU Dra -1.80     0.13
19    SW Dra -1.28     0.13
20    BK Dra -1.61     0.13
21    BB Eri -1.09     0.13
22    SZ Gem -1.46     0.13
23    SZ Hya -1.60     0.13
24    XX Hya -1.11     0.13
25    DD Hya -0.94     0.13
26    ST Leo -1.08     0.13
27    AX Leo -1.16     0.13
28    BX Leo -1.21     0.13
29    TT Lyn -1.53     0.13
30    TW Lyn -0.09     0.13
31    CN Lyr -0.38     0.13
32    IO Lyr -0.91     0.13
33    KX Lyr -0.22     0.13
34  V455 Oph -0.71     0.13
35    VZ Peg -1.78     0.13
36    DZ Peg -1.26     0.13
37    AR Per -0.29     0.13
38    XX Pup -1.33     0.13
39    HK Pup -1.11     0.13
40    KZ Pup -0.30     0.13
41    VY Ser -1.90     0.13
42    AP Ser -1.43     0.13
43     T Sex -1.37     0.13
44    SX UMa -1.45     0.13
45    TU UMa -1.57     0.13
46    AB UMa -0.65     0.13
47    AF Vir -1.21     0.13
48    BB Vir -1.30     0.13

### Solano et al. (1997)

### (see data on CDS, as well as Sec. 4 in Solano, E., Garrido, R., Fernley, J., & Barnes, T. 1997, A&ASS, 125, 321)

In [33]:
data_S97 = pd.read_csv(stem + "solano_1997_abundances.dat")

In [34]:
data_S97["err_feh"] = 0.18 # rms of difference Solano+ 97 found with literature values

In [35]:
data_S97

      name   feh  err_feh
0   SW And -0.36     0.18
1   AT And -1.14     0.18
2   TY Aps -0.92     0.18
3   XZ Aps -0.55     0.18
4   BV Aqr -1.18     0.18
5   RS Boo -0.31     0.18
6   AE Boo -1.18     0.18
7   RR Cet -1.31     0.18
8   DX Del -0.39     0.18
9   SU Dra -1.97     0.18
10  SW Dra -0.74     0.18
11  CS Eri -1.41     0.18
12  XZ Gru -1.37     0.18
13  XX Hya -1.22     0.18
14  IK Hya -1.24     0.18
15  FW Lup -0.20     0.18
16  TT Lyn -1.34     0.18
17  CN Lyr -1.10     0.18
18  KX Lyr -0.41     0.18
19  VY Nor -2.01     0.18
20  DH Peg -1.35     0.18
21  DZ Peg -1.21     0.18
22  VZ Peg -1.63     0.18
23  AR Per -0.23     0.18
24  VW Scl -0.84     0.18
25  VY Ser -1.53     0.18
26  AP Ser -1.62     0.18
27   T Sex -1.27     0.18
28  MT Tel -1.64     0.18
29  SX UMa -1.63     0.18
30  TU UMa -1.66     0.18
31  AM Vir -1.30     0.18

### Wallerstein & Huang (2010)

### (see Table 2 and Sec. 2 in Wallerstein, G., & Huang, W. 2010, arXiv:1004.2017)

In [20]:
data_W10 = pd.read_csv("wallerstein_huang_2010_abundances.dat")

In [21]:
data_W10

        name   feh
0   V445 Oph  0.24
1     RR Gem  0.01
2     SW And -0.16
3     DX Del -0.21
4     AR Per -0.32
5     KX Lyr -0.57
6     XZ Dra -0.75
7     UU Vir -0.90
8     BH Peg -1.17
9      W CVn -1.22
10    VZ Her -1.30
11    RV UMa -1.31
12    RR Leo -1.39
13    TT Lyn -1.41
14    RR Lyr -1.44
15    TU UMa -1.46
16    VX Her -1.48
17    DH Peg -1.53
18    RR Cet -1.61
19    ST Boo -1.77
20    SV Eri -1.94
21    RU Psc -2.04
22    RZ Cep -2.10
23     X Ari -2.68

### Liu et al. (2013)

### (see Tables 4, 5, and 7 in Liu, S., Zhao, G., Chen, Y.-Q., Takeda, Y., & Honda, S. 2013, RAA, 13, 1307)

In [7]:
data_L13 = pd.read_csv(stem + "liu_2013_abundances.dat")

In [8]:
# error is taken to be the quadrature combination of the abundance
# errors from FeI, FeII in stars RR Lyr and RS Boo (Tables 4 and 5).

data_L13["err_feh"] = np.sqrt(np.add(np.power(0.07,2),np.power(0.11,2)))

In [9]:
data_L13

        name  phase   feh   err_feh
0     AA Aql   0.61 -0.32  0.130384
1     AO Peg   0.77 -1.29  0.130384
2     AO Peg   0.79 -1.22  0.130384
3     BR Aqr   0.33 -0.69  0.130384
4     CI And   0.45 -0.43  0.130384
5     CN Lyr   0.53 -0.04  0.130384
6     DH Peg   0.08 -1.02  0.130384
7     DH Peg   0.41 -1.13  0.130384
8     DH Peg   0.70 -1.14  0.130384
9     DM Cyg   0.56  0.03  0.130384
10    DO Vir   0.36 -1.57  0.130384
11    DX Del   0.17 -0.13  0.130384
12    DX Del   0.35 -0.13  0.130384
13    DX Del   0.54 -0.15  0.130384
14    IO Lyr   0.26 -1.35  0.130384
15    KX Lyr   0.45 -0.27  0.130384
16    RR Cet   0.18 -1.35  0.130384
17    RR Lyr   0.90 -1.31  0.130384
18    RR Lyr   0.05 -1.41  0.130384
19    RR Lyr   0.06 -1.39  0.130384
20    RR Lyr   0.21 -1.40  0.130384
21    RR Lyr   0.36 -1.42  0.130384
22    RS Boo   0.31 -0.12  0.130384
23    SW And   0.35 -0.07  0.130384
24    TV Lib   0.40 -0.43  0.130384
25    TW Her   0.12 -0.35  0.130384
26    UU Cet   0.74 -1.36  0.130384
27  V413 Oph   0.80 -0.75  0.130384
28  V440 Sgr   0.15 -1.18  0.130384
29  V445 Oph   0.77  0.14  0.130384
30  V445 Oph   0.12  0.13  0.130384
31    VX Her   0.69 -1.33  0.130384
32    VY Ser   0.36 -1.85  0.130384
33    VY Ser   0.47 -1.83  0.130384
34    VY Ser   0.61 -1.82  0.130384
35    VY Ser   0.70 -1.80  0.130384

### Nemec et al. (2013)

### (see Table 7 in Nemec, J., Cohen, J., Ripepi, V., et al. 2013, ApJ, 773, 181)

In [11]:
data_N13 = pd.read_csv(stem + "nemec_2013_abundances.dat")

In [12]:
data_N13

            name   feh  err_feh
0         NR Lyr -2.54     0.11
1         FN Lyr -1.98     0.09
2         NQ Lyr -1.89     0.10
3       V350 Lyr -1.83     0.12
4       V894 Cyg -1.66     0.12
5         AW Dra -1.33     0.09
6    KIC 7030715 -1.33     0.08
7      V1107 Cyg -1.29     0.23
8       V368 Lyr -1.28     0.20
9    KIC 9658012 -1.28     0.14
10   KIC 9717032 -1.27     0.15
11      V715 Cyg -1.13     0.09
12     V2470 Cyg -0.59     0.13
13      V782 Cyg -0.42     0.10
14   KIC 6100702 -0.16     0.09
15      V839 Cyg -0.05     0.14
16      V784 Cyg -0.05     0.10
17     V2178 Cyg -1.66     0.13
18      V450 Lyr -1.51     0.12
19      V353 Lyr -1.50     0.20
20      V360 Lyr -1.50     0.29
21      V354 Lyr -1.44     0.16
22     V1104 Cyg -1.23     0.15
23      V808 Cyg -1.19     0.18
24      V783 Cyg -1.16     0.11
25      V366 Lyr -1.16     0.09
26      V355 Lyr -1.14     0.17
27  KIC 11125706 -1.09     0.08
28      V838 Cyg -1.01     0.10
29   KIC 9453114 -2.13     0.12
30   KIC 4064484 -1.58     0.13
31   KIC 3868420 -0.31     0.08
32   KIC 8832417 -0.27     0.11
33   KIC 5520878 -0.18     0.10
34         X Ari -2.74     0.09
35        VY Ser -1.71     0.07
36        ST Boo -1.62     0.06
37        UU Cet -1.33     0.08
38        RR Lyr -1.27     0.12
39        VX Her -1.23     0.12
40        RR Cet -1.18     0.09
41      V445 Oph  0.13     0.10
42        SW And  0.20     0.08

### Pancino et al. (2015)

### (see Table 7 in Pancino, E., Britavskiy, N., Romano, D., et al. 2015, MNRAS, 447, 755 2404)

In [13]:
data_P15 = pd.read_csv(stem + "pancino_2015_abundances.dat")

In [14]:
data_P15

     name   feh  err_feh
0   X Ari -2.19     0.17
1  VX Her -1.56     0.17
2  TU UMa -1.31     0.05

### Chadid et al. (2017)

### (see Table 3 in Chadid, M., Sneden, C., & Preston, G. W. 2017, ApJ, 835, 187)

In [16]:
data_C17 = pd.read_csv(stem + "chadid_2017_abundances.dat")

In [17]:
data_C17

         name  fehI  fehII  err_fehI  err_fehII
0      WY Ant -1.82  -1.77      0.14       0.16
1      BS Aps -1.51  -1.44      0.14       0.16
2      XZ Aps -1.65  -1.65      0.14       0.16
3      DN Aqr -1.77  -1.74      0.14       0.16
4      SW Aqr -1.39  -1.36      0.14       0.16
5       X Ari -2.60  -2.60      0.14       0.16
6      RR Cet -1.57  -1.56      0.14       0.16
7       W Crt -0.76  -0.74      0.14       0.16
8      DX Del -0.52  -0.58      0.14       0.16
9      SX For -1.80  -1.79      0.14       0.16
10     DT Hya -1.43  -1.35      0.14       0.16
11      V Ind -1.62  -1.59      0.14       0.16
12     SS Leo -2.36  -2.32      0.14       0.16
13     ST Leo -1.32  -1.29      0.14       0.16
14      Z Mic -1.46  -1.46      0.14       0.16
15     RV Oct -1.47  -1.44      0.14       0.16
16     UV Oct -1.69  -1.69      0.14       0.16
17   V445 Oph -0.05  -0.19      0.14       0.16
18     AV Peg -0.14  -0.20      0.14       0.16
19     HH Pup -0.95  -0.90      0.14       0.16
20     AN Ser  0.06   0.03      0.14       0.16
21     VY Ser -1.88  -1.87      0.14       0.16
22  V1645 Sgr -1.81  -1.79      0.14       0.16
23      W Tuc -1.77  -1.74      0.14       0.16
24     CD Vel -1.71  -1.73      0.14       0.16
25     AS Vir -1.59  -1.54      0.14       0.16
26     ST Vir -0.85  -0.86      0.14       0.16
27     UU Vir -0.93  -0.92      0.14       0.16

In [19]:
# For a net [Fe/H], take the mean abundance from the FeI and FeII lines.
# For the error, add those from FeHI and FeHII (which are means from the
# spectrum of that star) in quadrature.

data_C17["feh"] = data_C17[["fehI", "fehII"]].mean(axis=1)
data_C17["err_feh"] = np.sqrt(np.add(np.power(0.5*data_C17["err_fehI"],2),
                                     np.power(0.5*data_C17["err_fehII"],2)))

In [20]:
data_C17

         name  fehI  fehII  err_fehI  err_fehII    feh   err_feh
0      WY Ant -1.82  -1.77      0.14       0.16 -1.795  0.106301
1      BS Aps -1.51  -1.44      0.14       0.16 -1.475  0.106301
2      XZ Aps -1.65  -1.65      0.14       0.16 -1.650  0.106301
3      DN Aqr -1.77  -1.74      0.14       0.16 -1.755  0.106301
4      SW Aqr -1.39  -1.36      0.14       0.16 -1.375  0.106301
5       X Ari -2.60  -2.60      0.14       0.16 -2.600  0.106301
6      RR Cet -1.57  -1.56      0.14       0.16 -1.565  0.106301
7       W Crt -0.76  -0.74      0.14       0.16 -0.750  0.106301
8      DX Del -0.52  -0.58      0.14       0.16 -0.550  0.106301
9      SX For -1.80  -1.79      0.14       0.16 -1.795  0.106301
10     DT Hya -1.43  -1.35      0.14       0.16 -1.390  0.106301
11      V Ind -1.62  -1.59      0.14       0.16 -1.605  0.106301
12     SS Leo -2.36  -2.32      0.14       0.16 -2.340  0.106301
13     ST Leo -1.32  -1.29      0.14       0.16 -1.305  0.106301
14      Z Mic -1.46  -1.46      0.14       0.16 -1.460  0.106301
15     RV Oct -1.47  -1.44      0.14       0.16 -1.455  0.106301
16     UV Oct -1.69  -1.69      0.14       0.16 -1.690  0.106301
17   V445 Oph -0.05  -0.19      0.14       0.16 -0.120  0.106301
18     AV Peg -0.14  -0.20      0.14       0.16 -0.170  0.106301
19     HH Pup -0.95  -0.90      0.14       0.16 -0.925  0.106301
20     AN Ser  0.06   0.03      0.14       0.16  0.045  0.106301
21     VY Ser -1.88  -1.87      0.14       0.16 -1.875  0.106301
22  V1645 Sgr -1.81  -1.79      0.14       0.16 -1.800  0.106301
23      W Tuc -1.77  -1.74      0.14       0.16 -1.755  0.106301
24     CD Vel -1.71  -1.73      0.14       0.16 -1.720  0.106301
25     AS Vir -1.59  -1.54      0.14       0.16 -1.565  0.106301
26     ST Vir -0.85  -0.86      0.14       0.16 -0.855  0.106301
27     UU Vir -0.93  -0.92      0.14       0.16 -0.925  0.106301

# Sneden et al. 2017

# (See Tables 1, 4, and 6 in Sneden, Preston, Chadid, and Adamów, 2017 ApJ 848:68)

In [7]:
data_S17 = pd.read_csv(stem + "sneden_2017_abundances.dat")

In [9]:
data_S17["err_feh"] = np.sqrt(np.add(np.power(0.5*data_S17["err_fehI"],2),
                                     np.power(0.5*data_S17["err_fehII"],2)))

In [10]:
data_S17

        name   feh  epoch  err_fehI  err_fehII   err_feh
0     SC Sci -2.28      1       NaN        NaN       NaN
1     CS Eri -1.88      1       NaN        NaN       NaN
2     RU Sex -2.10      1       NaN        NaN       NaN
3      T Sex -1.76      1      0.14       0.15  0.102591
4      T Sex -1.73      2       NaN        NaN       NaN
5      Y Crv -1.39      1       NaN        NaN       NaN
6     AU Vir -2.04      1       NaN        NaN       NaN
7     MT Tel -2.58      1       NaN        NaN       NaN
8     MT Tel -1.17      2       NaN        NaN       NaN
9     YZ Cap -1.50      1       NaN        NaN       NaN
10  V701 Pup -2.50      1       NaN        NaN       NaN
11  V701 Pup -1.50      2       NaN        NaN       NaN
12  V701 Pup -1.98      3       NaN        NaN       NaN
13  V701 Pup -1.60      4       NaN        NaN       NaN
14  V701 Pup -1.83      5       NaN        NaN       NaN
15  V701 Pup -2.66      6       NaN        NaN       NaN
16    BO Gru -1.24      1       NaN        NaN       NaN